/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alarms: typeof import('./src/components/Alarms.vue')['default']
    AlarmSetting: typeof import('./src/components/AlarmSetting.vue')['default']
    AlarmSettings: typeof import('./src/components/AlarmSettings.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Header2: typeof import('./src/components/Header2.vue')['default']
    Hint: typeof import('./src/components/Hint.vue')['default']
    ISrunAlarm: typeof import('~icons/srun/alarm')['default']
    ISrunBulb: typeof import('~icons/srun/bulb')['default']
    ISrunCaret: typeof import('~icons/srun/caret')['default']
    ISrunCheckmark: typeof import('~icons/srun/checkmark')['default']
    ISrunHome: typeof import('~icons/srun/home')['default']
    ISrunPlus: typeof import('~icons/srun/plus')['default']
    ISrunSearch: typeof import('~icons/srun/search')['default']
    ISrunTrashbin: typeof import('~icons/srun/trashbin')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SortBar: typeof import('./src/components/SortBar.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    TestArea: typeof import('./src/components/TestArea.vue')['default']
    TipsAndTricks: typeof import('./src/components/TipsAndTricks.vue')['default']
    ToggleButton: typeof import('./src/components/ToggleButton.vue')['default']
  }
}
